import timeStyle from './time'
import { convenient_gradation_test } from '../JavascriptTimeAgo.test'

describe('"time" style', function()
{
	it(`should format "time" style relative time (English)`, function()
	{
		convenient_gradation_test
		([
			'just now',
			'1 minute',
			'2 minutes',
			'5 minutes',
			'10 minutes',
			'15 minutes',
			'20 minutes',
			'half an hour',
			'half an hour',
			'half an hour',
			'half an hour',
			'1 hour',
			'1 hour',
			'1 hour',
			'2 hours',
			'3 hours',
			'4 hours',
			'5 hours',
			'6 hours',
			'7 hours',
			'8 hours',
			'9 hours',
			'10 hours',
			'11 hours',
			'12 hours',
			'13 hours',
			'14 hours',
			'15 hours',
			'16 hours',
			'17 hours',
			'18 hours',
			'19 hours',
			'20 hours',
			'1 day',
			'2 days',
			'3 days',
			'4 days',
			'5 days',
			'1 week',
			'2 weeks',
			'3 weeks',
			'1 month',
			'2 months',
			'3 months',
			'4 months',
			'half a year',
			'half a year',
			'half a year',
			'half a year',
			'half a year',
			'1 year',
			'1 year',
			'1 year',
			'2 years',
			'3 years',
			'100 years'
		],
		'en-US',
		timeStyle)
	})

	it(`should format "time" style relative time (Russian)`, function()
	{
		convenient_gradation_test
		([
			'только что',
			'1 минута',
			'2 минуты',
			'5 минут',
			'10 минут',
			'15 минут',
			'20 минут',
			'полчаса',
			'полчаса',
			'полчаса',
			'полчаса',
			'1 час',
			'1 час',
			'1 час',
			'2 часа',
			'3 часа',
			'4 часа',
			'5 часов',
			'6 часов',
			'7 часов',
			'8 часов',
			'9 часов',
			'10 часов',
			'11 часов',
			'12 часов',
			'13 часов',
			'14 часов',
			'15 часов',
			'16 часов',
			'17 часов',
			'18 часов',
			'19 часов',
			'20 часов',
			'1 день',
			'2 дня',
			'3 дня',
			'4 дня',
			'5 дней',
			'1 неделю',
			'2 недели',
			'3 недели',
			'1 месяц',
			'2 месяца',
			'3 месяца',
			'4 месяца',
			'полгода',
			'полгода',
			'полгода',
			'полгода',
			'полгода',
			'1 год',
			'1 год',
			'1 год',
			'2 года',
			'3 года',
			'100 лет'
		],
		'ru-RU',
		timeStyle)
	})
})